dataware-tools/app-common

package.json
package.json の `repository` の部分を修正
GitHub Package Registry がリポジトリを認識できるようにするため  
参考: https://qiita.com/nall/items/5e94f37288c3e796a85e
=> Fix `repository` in package.json

src/components/ConfimModal.stories.tsx, src/components/ConfirmModal.tsx, src/components/ConfirmModalBase.tsx, src/utils/window.tsx
- Support cancenl closing ConfirmModal
- Add feature for receiving react component as titile, body to ConfirmModalBase
- 中身を弄れたり，閉じるのをキャンセルできると便利なので
- Related https://github.com/dataware-tools/dataware-tools/issues/59
=> Support cancenl closing ConfirmModal

src/components/SearchForm.tsx
- Add inputProps to SearchForm props
- Improve customizability
- Related https://github.com/dataware-tools/dataware-tools/issues/14
=> Add inputProps to SearchForm props

src/components/ConfimModal.stories.tsx, src/components/ConfirmModal.tsx
- 確認モーダルに削除時用のスタイルを追加
- Button.color に 'error' を入れて実現
- Material UI v5 alpha だと型エラーが出るが、 beta で解決する予定のため `@ts-expect-error` で回避
削除時の確認モーダルでボタンの色を赤に変更したい
- Issue: https://github.com/dataware-tools/dataware-tools/issues/27
=> Add delete mode to confirm modal

src/api/fetchClient.tsx
- Add utility for extracting error message from fetch error
- フロントアプリで表示するフェッチに関わるエラーメッセージのうち，一般的なものの処理は共通化したいため
- Related https://github.com/dataware-tools/dataware-tools/issues/63
=> Add utility for extracting common error message from fetch error

bin/esbuild.js, package-lock.json, package.json, tsconfig.json
- Use esbuild for bundling instead of microbundle
- https://github.com/dataware-tools/app-common/issues/67 を解決して，フェッチ用の Hook を共通化できるようにしたいので
- [単純にビルドが早くなるため](https://github.com/evanw/esbuild#why)
- Related https://github.com/dataware-tools/dataware-tools/issues/73
=> Use esbuild for bundling instead of microbundle

.github/workflows/test.yaml, package.json
- Drop support for Node 10
Node 10 is not LTS now
=> Drop support for Node 10

.github/workflows/test-apps.yaml
Add CI to test apps which use app-common
To avoid destructive changes
=> Add CI to test apps which use app-common

.github/workflows/auto-release.yml
Stop automatic release when Dependabot push
github.head_ref は PR 時にしか参照できなず，上手く動いていなかったので
=> Stop automatic release when Dependabot push

.github/workflows/auto-merge.yml
Add CI for automaticaly merging dependabot patch update
依存関係のパッチバージョンのアップデートは，CI が通れば自動でマージして欲しいので
https://github.com/ridedott/merge-me-action
=> Add CI for automaticaly merging dependabot patch update

src/utils/hooks.ts, src/utils/index.ts
Add hooks for using eventListening
Window で発火したイベント( onbeforeunload とか)をトリガーにして色々やりたいから
Related https://github.com/dataware-tools/dataware-tools/issues/117
=> Add hooks for using eventListening

.release-it.json
release-itの設定に `github.release: true` を追加
2022/3/15あたりからrelease-itが動作していない
https://github.com/dataware-tools/app-common/actions/workflows/auto-release.yml
https://github.com/release-it/release-it/blob/14.14.3/docs/github-releases.md#automated
=> Add github.release setting to release-it

.github/workflows/auto-release.yml
auto-release CIの環境変数 `NODE_AUTH_TOKEN` を `GITHUB_TOKEN` に変更
- auto-releaseが動かない
- release-itのドキュメントにはGITHUB_TOKEN環境変数を確認するとあったため
https://github.com/release-it/release-it/blob/14.14.3/docs/github-releases.md#automated
=> Change env var of auto-release CI to GITHUB_TOKEN

.github/workflows/test.yaml, package.json
Drop node v12 from supporting
Node v12 is not maintained now
=> Drop node v12 from supporting

.github/workflows/auto-release.yml
Skip release ci on renovate PR
renovate が依存関係を更新するときにはリリースしたくないから
=> Skip release ci on renovate PR

.github/workflows/auto-release.yml
Fix trigger of auto-release
To skip auto-release when renovate's PR merged to master branch
Fix trigger of auto-release
=> Fix trigger of auto-release

package-lock.json, package.json
アップデート後は CI が失敗するので戻す
https://github.com/dataware-tools/app-common/runs/7212449668?check_suite_focus=true
Reverts dataware-tools/app-common#438
=> Revert "Update dependency @csmith/release-it-calver-plugin to v2022"

package-lock.json, package.json
Bump package version to fix error on CI
[Automatic release workflow](https://github.com/dataware-tools/app-common/runs/7316000117?check_suite_focus=true#step:8:282) がバグってたから
=> Bump package version to fix error on CI

src/components/toast/index.ts, src/components/toast/utils.tsx
エラー通知のトーストを表示する関数をapp-commonに移動
各アプリで共通しているため
- https://github.com/dataware-tools/app-data-browser-next/pull/485
- https://github.com/dataware-tools/app-user-manager/pull/367
=> Add utility function that enqueues error toast

.github/workflows/auto-release.yml
Add Ci for publishing to npm on release in github
Github のリリース時に npm に publish する方が諸々都合がいいから
https://github.com/dataware-tools/app-common/releases/tag/v0.0.0-test1
=> Add Ci for publishing to npm on release in github

package-lock.json, package.json, src/components/MultiSelect.tsx
Bump react toastify to v9 with dev tools
react-toastify v9 を使いたい
[react-toastify は webpack v4 では動作しないっぽい
](https://github.com/fkhadra/react-toastify/issues/775#issuecomment-1149567156)
https://github.com/dataware-tools/dev-tools-for-apps/pull/128
=> Bump react toastify to v9 with dev tools
