dataware-tools/app-common

src/api/catalog.ts, src/app/catalog.ts, src/components/Footer.tsx, src/components/Header.tsx, src/components/MultiSelect.tsx, src/components/PerPageSelect.tsx, src/components/Sample.test.tsx, src/components/Sample.tsx, src/components/TabBar.tsx, src/components/TableRow.tsx, src/components/dialog/DialogCloseButton.tsx, src/test-utils.tsx, src/utils/window.tsx, tsconfig.json
- Disable baseUrl
- Micro-bundle does not resolve baseUrl
=> Disable baseUrl

src/utils/window.tsx
- Apply theme to ConfirmModal
- bug fix
=> Apply theme to ConfirmModal

.storybook/preview.js, src/components/Footer.tsx, src/components/Header.tsx, src/components/dialog/DialogBody.tsx, src/components/dialog/DialogContainer.tsx, src/components/dialog/DialogMain.tsx, src/components/dialog/DialogTemplate.stories.tsx, src/components/dialog/DialogTemplate.tsx, src/components/dialog/DialogWrapper.tsx, src/components/page/PageBody.tsx, src/components/page/PageContainer.tsx, src/components/page/PageMain.tsx, src/components/page/PageWrapper.tsx
- Use M-ui system prop for layouting page and dialog
- 色々な CSS プロパティを props として渡せるようになって便利だから
- https://github.com/dataware-tools/dataware-tools/issues/43 を解決するために必要だから
- https://github.com/dataware-tools/dataware-tools/issues/28 を解決するために必要だから
=> Use M-ui system prop for layouting page and dialog

src/components/dialog/DialogCloseButton.tsx
- Fix bug that theme is null
- bug fix
=> Fix bug that theme is null

src/theme.ts
- Add DataGrid theme
- Table コンポーネントと大体同じ見た目にするため
=> Add DataGrid theme

src/api/fetchClient.tsx
- Add util for fetching
- エラーメッセージの処理方法を共通化したいから
=> Add util for fetching

.prettierignore, .stylelintrc.js, README.md, jest.config.js, lint-staged.config.js
- Fix code format of misc config file
- 揃ってないのが気になったので
=> Fix code format of misc config file

src/components/Header.tsx
- Fix auth config
- 今までの設定では，Auth0 の管理ページから redirect_uri をホワイトリストに追加する必要があったから
=> Fix auth config

.github/workflows/test.yaml
=> Add test to CI

.github/workflows/test.yaml
- Execute test on multiple node versions
- ライブラリの汎用性を高くしたいから
- Related https://github.com/dataware-tools/dataware-tools/issues/78
=> Execute test on multiple node versions

package.json
- Add react-dom to peerDeps
- 入れ忘れていた
=> Add react-dom to peerDeps

package-lock.json, package.json, src/theme.ts
- MUI のテーマに使用する型定義を修正
- tsc のエラーを無視するコメントを外したかったので
- https://mui.com/components/data-grid/getting-started/#typescript
=> Fix theme type

src/api/route.ts, src/auth/config.ts
注入できる環境変数名の変更
現在使用しているフロント用のフレームワークは，ホワイトリスト方式で任意の名前で環境変数を注入できることが分かったので，名前を統一したい
=> Fix injectable env var

.github/dependabot.yaml
Add dependabot setting
Manual updating dependencies may be annoying task
=> Add dependabot setting

.github/workflows/auto-release.yml
Use node 16 instead of 14
Node 16 が LTS になったので
=> Use node 16 instead of 14

.github/workflows/auto-release.yml
- Stop releasing when branch name contains "depandabot"
知らないうちに頻繁にリリースされたりしていたので
頻繁にリリースされると CI がバグりがちなので
=> [skip ci] Stop releasing when branch name contains "depandabot"

.github/workflows/test-apps.yaml
Add test app
app-launcher-next も app-common に依存しているので
=> Add test app

.github/workflows/auto-merge.yml
Fix to update dependabot minor update
諸々テストが追加されて，パッチバージョンでもテストが通れば自動でマージしていいくらいになったと思うので
https://github.com/dataware-tools/app-common/pull/154
https://github.com/dataware-tools/app-common/pull/146
=> Fix to update dependabot minor update

src/index.ts
Export FilterSelectorList
export するのを忘れていたので
=> Export FilterSelectorList

package-lock.json, package.json, src/api/fetchClient.tsx
Add util types for fetching
フェッチのインターフェースを出来る限り統一したいので
=> Add util types for fetching

src/components/SearchForm.tsx
Fix bug that icon button not work correctly when enabled history
Bug fixes
=> Fix bug that icon button not work correctly when enabled history

src/components/FilterSelector.tsx
Fix color of line in FilterSelector
To be more harmonic with other components
=> Fix color of line in FilterSelector

.storybook/preview.js, src/components/MultiSelect.tsx, src/index.ts, src/test-utils.tsx, src/theme.ts, src/utils/window.tsx
Support changing font
To improve usability
=> Support changing font

src/components/SearchForm.tsx
Improve UX of search box with hitsory
To improve UX
https://github.com/hdwlab/nu-lecture-search-system/pull/85
=> Improve UX of search box with hitsory

src/components/MultiSelect.test.tsx, src/components/MultiSelect.tsx
Fix the test of `MultSelect`
As it was not working properly due to #320
=> Fix the test of MultiSelect

.github/workflows/test-apps.yaml
Add registry-url to auth github packages
Fix CI failure
=> Add registry-url to auth github packages

.github/workflows/auto-release.yml, .gitignore, package-lock.json, package.json
Fix failure of CI for auto releasing package
自動リリース用のCIが失敗していたので
↓ 失敗していたマージコミット
https://github.com/dataware-tools/app-common/runs/6809147721?check_suite_focus=true
↓ 成功を確認したこのPR内のコミット
https://github.com/dataware-tools/app-common/runs/6810397496?check_suite_focus=true
=> Fix failure of CI for auto releasing package

package-lock.json, package.json, src/components/Spacer.test.tsx, src/components/TableRow.tsx, src/test-utils.tsx
Bump eslint-config
eslint v8 が出て長いこと経ったのでアップデートしたい
=> Bump eslint-config

src/theme.ts
Import themeAugmentation from mui/lab
推奨されてる方法だから
See: https://mui.com/material-ui/about-the-lab/#typescript
=> Import themeAugmentation from mui/lab
